version: '2'
services:
  nginx:
    image: nginx:1.15
    restart: always
    ports:
    - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/logs/:/var/log/nginx/
    links:
      - gitbook
    networks:
      - gitbook
  gitbook:
    build: .
    container_name: gitbook
    restart: always
    ports:
    - "4000:4000"
    - "35729:35729"
    volumes:
      - /data/gitbook:/gitbook
    networks:
      - gitbook
networks:
  gitbook:
    ipam:
      config:
      - subnet: 10.220.0.0/16
